name: release
on:
  push:
    branches:
      - 'master'

jobs:

  build:
    if: github.repository == 'kpaas-io/test-action'
    name: make execution file
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: calc tag
        run: |
          tag=`date +%Y%m%d%H%M%S`
          echo "::set-output name=TAG::${tag}"
        id: calc-tag

      - name: Print Version
        run: |
          echo "${version}"
        env:
          version: ${{ steps.calc-tag.outputs.TAG }}

      - name: Make file
        run: |
          go build main.go
